#!/usr/bin/env python3
"""Generate and validate an offline QA scenario proposal from a requirement."""

import argparse
import json
from pathlib import Path


def load_json(path):
    with path.open(encoding="utf-8") as file:
        return json.load(file)


def require(condition, message):
    if not condition:
        raise ValueError(message)


def validate_requirement(requirement):
    required = ["schemaVersion", "requirementId", "title", "description", "acceptanceCriteria", "applicationContext"]
    for field in required:
        require(field in requirement, f"requirement missing field: {field}")
    require(requirement["schemaVersion"] == "1.0", "unsupported requirement schemaVersion")
    require(requirement["acceptanceCriteria"], "acceptanceCriteria must not be empty")
    context = requirement["applicationContext"]
    for field in ["baseUrl", "interfaces", "knownConstraints"]:
        require(field in context, f"applicationContext missing field: {field}")


def scenario(requirement_id, number, title, test_type, priority, data, steps, expected, tags):
    return {
        "scenarioId": f"{requirement_id}-S{number:02d}",
        "title": title,
        "requirementReference": requirement_id,
        "preconditions": ["TaskFlow API is running", "The test database is reset for the scenario"],
        "testData": data,
        "steps": steps,
        "expectedResult": expected,
        "priority": priority,
        "testType": test_type,
        "automationCandidate": True,
        "tags": tags,
    }


def generate(requirement):
    requirement_id = requirement["requirementId"]
    return {
        "schemaVersion": "1.0",
        "sourceRequirement": requirement_id,
        "review": {
            "status": "needs-review",
            "notes": [
                "Generated by the offline Phase C generator; human review is required.",
                "Duplicate-title policy, list ordering, and security behavior are not specified by the requirement.",
            ],
        },
        "scenarios": [
            scenario(requirement_id, 1, "Create a task with title and description", "positive", "high", {"title": "Prepare release notes", "description": "Summarize the release"}, ["POST /tasks with a valid title and description"], ["Response status is 201", "Response contains a generated numeric id", "Location header identifies the new task", "Response preserves title and description"], ["smoke", "api", "regression"]),
            scenario(requirement_id, 2, "Create a task with title only", "positive", "high", {"title": "Review test results"}, ["POST /tasks with a valid title and no description"], ["Response status is 201", "Task is persisted with an optional description"], ["smoke", "api"]),
            scenario(requirement_id, 3, "Reject a blank title", "validation", "high", {"title": "   ", "description": "Invalid task"}, ["POST /tasks with whitespace-only title"], ["Response status is 400", "Response identifies the title validation error", "No task is created"], ["validation", "negative"]),
            scenario(requirement_id, 4, "Reject a missing title", "validation", "high", {"description": "Missing title"}, ["POST /tasks without a title field"], ["Response status is 400", "Response provides useful validation details", "No task is created"], ["validation", "negative"]),
            scenario(requirement_id, 5, "Retrieve the created task", "persistence", "high", {"title": "Retrieve me", "description": "Persistence check"}, ["POST /tasks with valid data", "Read the returned task ID", "GET /tasks/{id}"], ["GET response status is 200", "Retrieved task matches the created title and description"], ["smoke", "persistence", "regression"]),
            scenario(requirement_id, 6, "Reject malformed JSON", "error-handling", "medium", {"body": "{\"title\":", "contentType": "application/json"}, ["POST /tasks with malformed JSON"], ["Request is rejected with a client-error response", "The server does not create a partial task"], ["negative", "api"]),
            scenario(requirement_id, 7, "Preserve unique generated IDs across creates", "boundary", "medium", {"firstTitle": "First task", "secondTitle": "Second task"}, ["POST /tasks twice with different valid titles"], ["Both requests succeed", "Generated IDs are present and distinct"], ["api", "persistence"]),
            scenario(requirement_id, 8, "Trace create behavior to the requirement", "regression", "medium", {"requirementId": requirement_id}, ["Run the approved create-task smoke scenarios"], ["Each automated result can be linked to the requirement and scenario ID"], ["regression", "traceability"]),
        ],
    }


def validate_output(output):
    require(output.get("schemaVersion") == "1.0", "unsupported scenario schemaVersion")
    require(output.get("review", {}).get("status") in {"generated", "needs-review", "approved", "rejected"}, "invalid review status")
    scenarios = output.get("scenarios", [])
    require(scenarios, "scenario output must not be empty")
    ids = set()
    required = ["scenarioId", "title", "requirementReference", "preconditions", "testData", "steps", "expectedResult", "priority", "testType", "automationCandidate", "tags"]
    for item in scenarios:
        for field in required:
            require(field in item, f"scenario missing field: {field}")
        require(item["scenarioId"] not in ids, f"duplicate scenario ID: {item['scenarioId']}")
        ids.add(item["scenarioId"])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    requirement = load_json(args.input)
    validate_requirement(requirement)
    output = generate(requirement)
    validate_output(output)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as file:
        json.dump(output, file, indent=2)
        file.write("\n")
    print(f"Generated {len(output['scenarios'])} scenarios for {requirement['requirementId']}")


if __name__ == "__main__":
    main()